EDCW/EDCW/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'', include('index.urls')),
    url(r'', include('contact.urls')),
    url(r'', include('community.urls')),
    url(r'^team/', include('teams.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'', include('login.urls')),
]

EDCW/community/urls.py
from django.conf.urls import url
from . import views

app_name = 'community'

urlpatterns = [
    url(r'^community_create$',views.community_create,name='community_create'),
    url(r'^community_index$',views.community_index,name='community_index'),
    url(r'^community_index?page=([0-9]+)$',views.community_index,name='community_index'),
    url(r'^community_index_tongzhi$',views.community_index_tongzhi,name='community_index_tongzhi'),
    url(r'^community_index_tongzhi?page=([0-9]+)$',views.community_index_tongzhi,name='community_index_tongzhi'),
    url(r'^community_index_jishu$',views.community_index_jishu,name='community_index_jishu'),
    url(r'^community_index_jishu?page=([0-9]+)$',views.community_index_jishu,name='community_index_jishu'),
    url(r'^community_index_shuitie$',views.community_index_shuitie,name='community_index_shuitie'),
    url(r'^community_index_shuitie?page=([0-9]+)$',views.community_index_shuitie,name='community_index_shuitie'),
    url(r'^community_index_mypost$',views.community_index_mypost,name='community_index_mypost'),
    url(r'^community_index_mypost?page=([0-9]+)$',views.community_index_mypost,name='community_index_mypost'),
    url(r'^community_content/(?P<id>[0-9]+)',views.community_content),
]
# Create your views here.

EDCW/contact/urls.py
from django.conf.urls import url
from . import views

app_name = 'contact'

urlpatterns = [
    url(r'^contact$', views.contact, name='contact'),
]

# Create your views here.

EDCW/index/urls.py
from django.conf.urls import url, include
from . import views
import contact
app_name = 'index'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^introduction$', views.introduction, name='introduction'),
    url(r'^notice$', views.noticeIndex, name='notice'),
    url(r'^rule$', views.rule, name='rule'),
    url(r'^download', views.download, name='download'),
]

EDCW/login/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'login'

urlpatterns = [
    url(r'^login$',views.Login,name='login'),
    ]
urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT )

EDCW/teams/urls.py
from django.conf.urls import url
from . import views

app_name = 'teams'

urlpatterns = [
    url(r'^index$', views.index , name='index'),
    url(r'^create$', views.create, name='create'),
    url(r'^info/(?P<team_id>[0-9]+)$', views.info, name='info'),
    url(r'^application/(?P<team_id>[0-9]+)$', views.application, name='application'),
    url(r'^myteam$', views.my_team, name='my_team'),
    url(r'^answer$', views.acceptOrReject, name='acceptOrReject'),
    url(r'^dismiss$', views.dismiss, name='dismiss'),
    url(r'group$', views.group, name='group'),
    url(r'choose_first_time$', views.choose_first_time, name='choose_first_time')
]

EDCW/login/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
from django.contrib.auth.models import User, AbstractUser
from django.db import models
from django.conf import settings
import os



@python_2_unicode_compatible
class Member(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile' )
    student_id = models.CharField(max_length=20, blank=True)
    is_leader = models.BooleanField(default=False)
    image = models.ImageField(upload_to='head_images',
                              default=os.path.join('head_images', 'custom.png'))
    def __str__(self):
        return self.user.username

EDCW/login/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(max_length=30,required=True)
    password = forms.CharField(max_length = 30,widget = forms.PasswordInput,required=True)
    

EDCW/login/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, HttpResponseRedirect,render_to_response
from django.contrib.auth.models import User
from django.conf import settings
from django.urls import reverse
from login.models import Member
from .forms import LoginForm
import urllib
import urllib.request
import json
import os
from django.contrib.auth import login,logout



def	get_access_token(username,password):
    auth_url = 'https://www.eesast.com/o/token/'
    body = urllib.parse.urlencode({
    'client_id':settings.EESAST_CLIENTID,
    'grant_type':'password',
    'username':username,
    'password':password,
    })
    body = body.encode('utf-8')
    headers = {'Content-Type':'application/x-www-form-urlencoded'}
    req = urllib.request.Request(auth_url, body, headers=headers)
    resp = urllib.request.urlopen(req)
    resp = resp.read()
    resp = resp.decode('utf-8')
    data = json.loads(resp)
    return data['access_token']

def get_user_info(access_token):
	if access_token:
		headers = {'Authorization': "Bearer %s" %access_token}
		userinfo_url = 'https://www.eesast.com/account/userinfo/'
		req = urllib.request.Request(userinfo_url,headers = headers)
		resp = urllib.request.urlopen(req)
		resp = resp.read()
		resp = resp.decode('utf-8')
		data = json.loads(resp)
		return data
	else:
		return none

def check_user(data):
    if not 'name' in data or not 'student_ID' in data:
        raise Exception
    try:
        user1 = User.objects.get(username=data['name'])
        print(user1.username)
        user1.profile.student_id = data['student_ID']
        user1.profile.save()
        return user1
    except User.DoesNotExist :
        user2 = User(username=data['name'])
        user2.save()
        member = Member(user=user2, student_id=data['student_ID'])
        member.save()
        return user2

def Login(request):
    error = ''
    access_token=''
    if_logout=''


    if request.method =='POST':

        if request.user.is_authenticated:
            if 'logout' in request.POST:
                Logout(request)
            else:
                error = Get_Image(request)
                return render(request, 'login/login.html', {'error':error})

        else:
            form = LoginForm(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                try:
                    access_token = get_access_token(cd['username'],cd['password'])
                    data = get_user_info(access_token)
                    user = check_user(data)
                    login(request,user)
                except Exception:
                    error = '登录申请失败！请确认用户名与密码是否正确，以及学号与姓名信息是否完整!'
    else:
        form = LoginForm()
    return render(request, 'login/login.html', {'error':error})

def Get_Image(request):
    profile=request.user.profile
    old_name = profile.image.name

    if not 'image' in request.FILES:
        return '请上传一个文件'

    photo=request.FILES['image']
    name=photo.name.lower()

    if not name.endswith(('.jpg', '.png', '.jpeg', '.gif')):
        return '请上传一个规范格式的图片'




    # for compatibale reason
    if old_name.startswith('/'):
        profile.image.name = os.path.join('head_images', os.path.split(old_name)[-1])
        profile.save()

    old_path = profile.image.path

    # delete the previous avatar
    if profile.image.name != os.path.join('head_images', 'custom.png'):
        if os.path.exists(old_path):
            os.remove(old_path)

    # bind the new avatar to profile
    profile.image=photo
    profile.save()
    initial_path=profile.image.path

    # rename the new avatar to a regular name, and meanwhile, place the avatar
    # at a required place (using os.rename)
    suffix = name.split('.')[-1]
    profile.image.name=os.path.join(
        'head_images',
        'user_%s_%s.%s' % (request.user.username, request.user.id, suffix)
    )
    new_path=os.path.join(settings.MEDIA_ROOT, profile.image.name)
    os.rename(initial_path,new_path)
    profile.save()






def Logout(request):
	logout(request)
	return HttpResponseRedirect("/index")



def ResetPassword(request):


	return HttpResponseRedirect("www.EESAST/account/resetpasswordrequest")

EDCW/login/templates/login.html
{% load static %}
<!doctype html>
        <!--[if lt IE 7]> <html class="lt-ie9 lt-ie8 lt-ie7" lang="en-US"> <![endif]-->
        <!--[if IE 7]>    <html class="lt-ie9 lt-ie8" lang="en-US"> <![endif]-->
        <!--[if IE 8]>    <html class="lt-ie9" lang="en-US"> <![endif]-->
        <!--[if gt IE 8]><!--> <html lang="zh-CN"> <!--<![endif]-->
        <head>
                <!-- META TAGS -->
                <meta charset="UTF-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
				<meta name="description" content="community">
	            <meta name="author" content="zw">

                <title>第十八届电子设计大赛</title>

                
				
                <!-- Style Sheet-->
                <link rel="shortcut icon" href="{% static 'login/img/电设18.png' %}" />
                <link rel='stylesheet' id='bootstrap-css-css'  href="{% static 'login/css/bootstrap.css' %}" type='text/css' media='all' />
                <link rel='stylesheet' id='responsive-css-css'  href="{% static 'login/css/responsive.css' %}" type='text/css' media='all' /> 
                <!--<link rel='stylesheet' id='pretty-photo-css-css'  href='js/prettyphoto/prettyPhotoaeb9.css?ver=3.1.4' type='text/css' media='all' />-->
                <link rel='stylesheet' id='main-css-css'  href="{% static 'login/css/login.css' %}" type='text/css' media='all' />
                <!--<link rel='stylesheet' id='custom-css-css'  href='css/custom5152.html?ver=1.0' type='text/css' media='all' />-->


                <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
                <!--[if lt IE 9]>
                <script src="js/html5.js"></script></script>
                <![endif]-->


        </head>
		<script type="text/javascript"> 
var isIE = /msie/i.test(navigator.userAgent) && !window.opera; 
function fileChange(target,id) { 
var fileSize = 0; 
var filetypes =[".jpg",".png",".rar",".txt",".zip",".doc",".ppt",".xls",".pdf",".docx",".xlsx"]; 
</script> 

        <body>

                <!-- Start of Header -->
                <div class="header-wrapper">
                        <header>
                                <div class="container">
								
                                        <div class="logo-container">
                                                <!-- Website Logo -->
                                                <a href="{% url 'index:index' %}"  id="eesast" style="font-size:17px; font-weight:bold;">
                                                      天赐良机
                                                </a>
                                             
                                        </div>


                                        <!-- Start of Main Navigation -->
                                        <nav class="main-nav">
                                                <div class="menu-top-menu-container">
                                                        <ul id="menu-top-menu" class="clearfix">
                                                                <li><a href="{% url 'index:index' %}">主页</a></li>
                                                                <li ><a href="{% url 'index:introduction' %}">赛事介绍</a></li>
                                                                <li><a href="{% url 'teams:index' %}">组建队伍</a></li>
                                                                {% if request.user.is_authenticated %}
                                                                <li  class="current-menu-item"><a href="{% url 'login:login' %}">用户</a></li>
																{% endif %}
																{% if not request.user.is_authenticated %}
																<li  class="current-menu-item"><a href="{% url 'login:login' %}">登录</a></li>
																{% endif %}
                                                                <li><a href="{% url 'community:community_index' %}">论坛</a></li>
                                                                <li><a href="{% url 'index:notice' %}">文件</a></li>
																<li><a href="{% url 'index:rule' %}">比赛规则</a></li>
                                                                <li><a href="#">更多</a>
                                                                        <ul class="sub-menu">
                                                                                <li><a href="http://www.eesast.com">关于我们</a></li>
                                                                                <li><a href="{% url 'contact:contact' %}">联系我们</a></li>
                                                                        </ul>
                                                                </li>
                                                        </ul>
														<ul id="menu-top-right" class="clearfix">
														        {% if request.user.is_authenticated %}
                                                                                <li style="font-size:18px;bold"><a href="{% url 'login:login' %}"> {{request.user.username}}</a></li>

                                                                {% endif %}
														        <li><a href="https://www.eesast.com">电子系科协</a></li>
																<li style="font-family:'HelveticaNeue', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 15px; color: #c1cad1;">自动化系科协</li>
														</ul>
                                                </div>
                                        </nav>
                                        <!-- End of Main Navigation -->

                                </div>
                        </header>
                </div>
                <!-- End of Header -->

                <!-- Start of Search Wrapper -->
                <div class="search-area-wrapper">
                        <div class="search-area container">
                                <h2 class="search-header">第十八届电子设计大赛</h2>
                                <p class="search-tag-line">开始你的设计</p>
                        </div>
                </div>
                <!-- End of Search Wrapper -->
				
				<!-- Start of Page Container -->
                <div class="page-container">
                        <div class="container" id="page">
                                <div class="row">

                                        <!-- start of page content -->
                                        <div class="span8 page-content">
											{% if request.user.is_authenticated %}
												<article class="type-page hentry clearfix">
												        <img alt="" src="{{request.user.profile.image.url}}" class="avatar avatar-60 photo" height="60" width="60" style="display:inline; border-radius:60px;">
												        <h1 class="post-title" style="display:inline; padding:10px;">{{request.user.username}}，你好！</h1>
														<div onclick = "document.getElementById('image_upload').style.display='block'"><button class="clean-gray" onchange="fileChange(this);">上传头像</button></div>
																
                                                        
                                                                                                <div id='image_upload' style="display:none;">
																								<form action="" method="post" enctype="multipart/form-data">
																									{% csrf_token %}
																									<input id="id_image" type="file" class="" name="image"> 
																									<input type="submit" value="Submit" />
																								</form>
																								</div>
												        
														<hr>
														<table class="table table-striped table-bordered">
														  <tr>
														    <td>用户名</td>
															<td>{{request.user.username}}</td>
														  </tr>
														  <tr>
														    <td>学号</td>
															<td>{{request.user.profile.student_id}}</td>
														  </tr>
														</table>
												
												</article>
                                                <form action="" method="post">
												{% csrf_token %}
											     <input type="hidden" name="logout" value="zhuxiao"> 
											     <button class="btn btn-lg btn-info" onclick="form.submit();" title="登出">注销</button>
											   </form>												
											
                                        
												{% else %}
												<article class="type-page hentry clearfix">
                                                        <h1 class="post-title">
                                                                <a href="#">登录</a>
                                                        </h1>
                                                        <hr>
                                                        <p>请用科协用户名登录&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
                                                        <a href="https://www.eesast.com/account/simplesignup">还没有注册？点击前往注册</a></p>
                                                </article>


                                                <form id="contact-form" class="row" action="#" method="post">
													{% csrf_token %}

                                                        <div class="span2">
                                                                <label for="name">用户名 <span>*</span> </label>
                                                        </div>
                                                        <div class="span6">
                                                                <input type="text" name="username" id="name" class="required input-xlarge" value="" title="* Please provide your name">
                                                        </div>

                                                        <div class="span2">
                                                                <label for="password" style="display:inline;">密码<span>*</span></label>&nbsp&nbsp&nbsp
																<a href="https://www.eesast.com/account/resetpasswordrequest" style="display:inline; font-size:15px;">找回密码</a>
                                                        </div>
                                                        <div class="span6">
                                                                <input type="password" name="password" id="password" value="">
                                                        </div>
														 <div class="span2">
                                                                <label for="password">{{error}}</label>
                                                        </div>
														
													


                                                        <div class="span6 offset2 bm30">
                                                                <input type="submit" name="submit" value="Login" class="btn btn-inverse" style="width:150px;margin-top:50px;">
                                                                
                                                        </div>

                                                        <div class="span6 offset2 error-container"></div>
                                                        <div class="span6 offset2" id="message-sent"></div>

                                                </form>
											
											
										{% endif %}
										</div>
                                        <!-- end of page content -->


                                        <!-- start of sidebar -->
                                        <aside class="span4 page-sidebar">

                                                <section class="widget">
                                                        <div class="support-widget">
                                                                <h3 class="title">Welcome</h3>
                                                                <p class="intro">WHAT HURTS MORE? THE PAIN OF HARD WORK? OR THE PAIN OF REGRET?</p><a href="{% url 'contact:contact' %}">更多鸡汤请————联系我们</a>
                                                        </div>
                                                </section>

                                               

                                        </aside>
                                        <!-- end of sidebar -->
                                </div>
                        </div>
                </div>
                <!-- End of Page Container -->
				
				 <!-- Footer Bottom -->
                        <div id="footer-bottom-wrapper">
                                <div id="footer-bottom" class="container">
                                        <div class="row">
                                                <div class="span6">
                                                        <p class="copyright">
                                                                Copyright © All Rights Reserved by EESAST from Tsinghua
                                                        </p>
                                                </div>
                                                
                                        </div>
                                </div>
                        </div>
                        <!-- End of Footer Bottom -->

                </footer>
                <!-- End of Footer -->

                <a href="#top" id="scroll-top"></a>
				

                <!-- script -->
                <script type='text/javascript' src="{% static 'login/js/jquery.min.js' %}"></script>
				<script type='text/javascript' src="{% static 'login/js/custom.js' %}"></script>
				<script type='text/javascript' src="{% static 'login/js/jflickrfeed.js' %}"></script>
<script type='text/javascript' src="{% static 'login/js/jquery.validate.min.js' %}"></script>

        </body>
</html>