EDCW/EDCW/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'', include('index.urls')),
    url(r'', include('contact.urls')),
    url(r'', include('community.urls')),
    url(r'^team/', include('teams.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'', include('login.urls')),
]

EDCW/community/urls.py
from django.conf.urls import url
from . import views

app_name = 'community'

urlpatterns = [
    url(r'^community_create$',views.community_create,name='community_create'),
    url(r'^community_index$',views.community_index,name='community_index'),
    url(r'^community_index?page=([0-9]+)$',views.community_index,name='community_index'),
    url(r'^community_index_tongzhi$',views.community_index_tongzhi,name='community_index_tongzhi'),
    url(r'^community_index_tongzhi?page=([0-9]+)$',views.community_index_tongzhi,name='community_index_tongzhi'),
    url(r'^community_index_jishu$',views.community_index_jishu,name='community_index_jishu'),
    url(r'^community_index_jishu?page=([0-9]+)$',views.community_index_jishu,name='community_index_jishu'),
    url(r'^community_index_shuitie$',views.community_index_shuitie,name='community_index_shuitie'),
    url(r'^community_index_shuitie?page=([0-9]+)$',views.community_index_shuitie,name='community_index_shuitie'),
    url(r'^community_index_mypost$',views.community_index_mypost,name='community_index_mypost'),
    url(r'^community_index_mypost?page=([0-9]+)$',views.community_index_mypost,name='community_index_mypost'),
    url(r'^community_content/(?P<id>[0-9]+)',views.community_content),
]
# Create your views here.

EDCW/contact/urls.py
from django.conf.urls import url
from . import views

app_name = 'contact'

urlpatterns = [
    url(r'^contact$', views.contact, name='contact'),
]

# Create your views here.

EDCW/index/urls.py
from django.conf.urls import url, include
from . import views
import contact
app_name = 'index'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^introduction$', views.introduction, name='introduction'),
    url(r'^notice$', views.noticeIndex, name='notice'),
    url(r'^rule$', views.rule, name='rule'),
    url(r'^download', views.download, name='download'),
]

EDCW/login/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'login'

urlpatterns = [
    url(r'^login$',views.Login,name='login'),
    ]
urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT )

EDCW/teams/urls.py
from django.conf.urls import url
from . import views

app_name = 'teams'

urlpatterns = [
    url(r'^index$', views.index , name='index'),
    url(r'^create$', views.create, name='create'),
    url(r'^info/(?P<team_id>[0-9]+)$', views.info, name='info'),
    url(r'^application/(?P<team_id>[0-9]+)$', views.application, name='application'),
    url(r'^myteam$', views.my_team, name='my_team'),
    url(r'^answer$', views.acceptOrReject, name='acceptOrReject'),
    url(r'^dismiss$', views.dismiss, name='dismiss'),
    url(r'group$', views.group, name='group'),
    url(r'choose_first_time$', views.choose_first_time, name='choose_first_time')
]

EDCW/community/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from django import forms


class Post(models.Model):
	Category_List=(
		('1','赛事公告'),
		('2','技术讨论'),
		('3','各路水贴'),
		)
	title = models.CharField(u'评论标题',max_length=100)
	timestamp = models.DateTimeField(auto_now=True)
	content = models.TextField(u'内容',blank=True, null=True)
	sender = models.ForeignKey(User,on_delete=models.CASCADE)
	summary = models.CharField(u'摘要',blank=True, null=True,max_length=100)
	category = models.CharField(max_length = 1,default=1,choices=Category_List)
	priority = models.IntegerField(default=1000,verbose_name="优先级")
	def __unicode__(self):
		return self.title

class PostFile(models.Model):
    PERMISSION_CHOICES = {
        ('1',"公开"),
        ('2','登陆可见'),
    }
    post = models.ForeignKey(Post, on_delete = models.CASCADE)
    file_attached = models.FileField(upload_to='uploads/', blank=True,null=True)
    permissions = models.CharField(max_length=1,choices=PERMISSION_CHOICES)



class Comment(models.Model):
	post = models.ForeignKey(Post,related_name='p_comment')
	content= models.TextField(max_length=1000)
	replytime = models.DateTimeField(auto_now=True)
	replier = models.ForeignKey(User,null=True,on_delete=models.CASCADE)
	def __unicode__(self):
		return u'%s to post %s' %(self.replier,self.post)













# Create your models here.

EDCW/community/forms.py
# -*- coding:utf-8 -*-
from django import forms


class PostForm(forms.Form):
	Category_List=(
		('1','赛事公告'),
		('2','技术讨论'),
		('3','各路水贴'),
		)
	category = forms.CharField(widget=forms.RadioSelect(
		choices=Category_List), 
		)
	title = forms.CharField(max_length=100,error_messages={'required':u'标题不能为空'})
	outline = forms.CharField(max_length=100,required=False)
	body = forms.CharField(max_length=100,error_messages={'required':u'正文不能为空'})


class CommentForm(forms.Form):
	comment= forms.CharField(max_length=1000)

EDCW/community/views.py
# -*-  coding:utf-8 -*-
from django.shortcuts import render, render_to_response,HttpResponseRedirect
from community import forms
from community.models import Post,PostFile,Comment
from django.core.paginator import Paginator, InvalidPage, EmptyPage, PageNotAnInteger
from django.contrib.auth import authenticate, login
from community.forms import PostForm,CommentForm

Category_List=(
		('1','赛事公告'),
		('2','技术讨论'),
		('3','各路水贴'),
		)

def community_content(request,id):
	try:
		post = Post.objects.get(id=int(id))
	except:
		HttpResponseRedirect('/community_index')
	delete_id = None
	delete_id = request.POST.get('delete_id','')
	try:
		delcomment = Comment.objects.get(id=int(delete_id))
		delcomment.post.save()
		delcomment.delete()
	except Exception:
		pass
	if 	request.user.is_authenticated() :
		if request.method=='POST':
			form = CommentForm(request.POST)
			if form.is_valid():
				cd = form.cleaned_data
				comment = Comment(content=cd['comment'],post = Post.objects.get(id=int(id)),replier=request.user)
				comment.save()
				comment.post.save()
			else:
				form = CommentForm()
			print(4)
		commentlist = post.p_comment.all()
		return render(request,'community_content_after_login.html',{'post':post,'commentlist':commentlist})
	else:
		commentlist = post.p_comment.all()
		return render(request,'community_content.html',{'post':post,'commentlist':commentlist})



def community_create(request):
	if request.method == 'POST':
		form = PostForm(request.POST)
		print(form.errors)
		if form.is_valid():
			cd = form.cleaned_data
			post = Post(title=cd['title'],content=cd['body'],sender=request.user,summary=cd['outline'],category=cd['category'])
			post.save()
			return HttpResponseRedirect('/community_index')
	else:
		form = PostForm()
	return render(request,'community_create.html', {'form': form})





def community_index(request,page=1):
	post_list = Post.objects.order_by('priority','-timestamp')
	paginator = Paginator(post_list,5)
	delete_id = None
	delete_id = request.POST.get('delete_id','')
	if request.user.is_authenticated():
		print(1)
	try:
		post = Post.objects.get(id=int(delete_id))
		post.delete()
	except Exception:
		pass
	try:
		page = int (request.GET.get('page','1'))
	except ValueError:
		page = 1
	try:
		posts = paginator.page(page)
	except (EmptyPage,InvalidPage):
		posts = paginator.page(paginator.num_pages)
	for i in range(page,page+3):
		if i > paginator.num_pages:
			break
		maxpage = i
	for i in range(page,page-3,-1):
		if i < 1:
			break
		minpage = i
	pagerange=range(minpage,maxpage+1)
	if request.user.is_authenticated():
		return render(request,'community_index_after_login.html',{"posts":posts,"pagerange":pagerange,})
	else:
		return render(request,'community_index.html',{"posts":posts,"pagerange":pagerange,})

def community_index_tongzhi(request,page=1):
	post_list = Post.objects.filter(category='1')
	paginator = Paginator(post_list,5)
	delete_id = None
	delete_id = request.POST.get('delete_id','')
	try:
		post = Post.objects.get(id=int(delete_id))
		post.delete()
	except Exception:
		pass
	try:
		page = int (request.GET.get('page','1'))
	except ValueError:
		page = 1
	try:
		posts = paginator.page(page)
	except (EmptyPage,InvalidPage):
		posts = paginator.page(paginator.num_pages)
	for i in range(page,page+3):
		if i > paginator.num_pages:
			break
		maxpage = i
	for i in range(page,page-3,-1):
		if i < 1:
			break
		minpage = i
	pagerange=range(minpage,maxpage+1)
	if request.user.is_authenticated():
		return render(request,'community_index_after_login.html',{"posts":posts,"pagerange":pagerange,})
	else:
		return render(request,'community_index.html',{"posts":posts,"pagerange":pagerange,})

def community_index_jishu(request,page=1):
	post_list = Post.objects.filter(category='2')
	paginator = Paginator(post_list,5)
	delete_id = None
	delete_id = request.POST.get('delete_id','')
	try:
		post = Post.objects.get(id=int(delete_id))
		post.delete()
	except Exception:
		pass
	try:
		page = int (request.GET.get('page','1'))
	except ValueError:
		page = 1
	try:
		posts = paginator.page(page)
	except (EmptyPage,InvalidPage):
		posts = paginator.page(paginator.num_pages)
	for i in range(page,page+3):
		if i > paginator.num_pages:
			break
		maxpage = i
	for i in range(page,page-3,-1):
		if i < 1:
			break
		minpage = i
	pagerange=range(minpage,maxpage+1)
	if request.user.is_authenticated():
		return render(request,'community_index_after_login.html',{"posts":posts,"pagerange":pagerange,})
	else:
		return render(request,'community_index.html',{"posts":posts,"pagerange":pagerange,})

def community_index_shuitie(request,page=1):
	post_list = Post.objects.filter(category='3')
	paginator = Paginator(post_list,5)
	delete_id = None
	delete_id = request.POST.get('delete_id','')
	try:
		post = Post.objects.get(id=int(delete_id))
		post.delete()
	except Exception:
		pass
	try:
		page = int (request.GET.get('page','1'))
	except ValueError:
		page = 1
	try:
		posts = paginator.page(page)
	except (EmptyPage,InvalidPage):
		posts = paginator.page(paginator.num_pages)
	for i in range(page,page+3):
		if i > paginator.num_pages:
			break
		maxpage = i
	for i in range(page,page-3,-1):
		if i < 1:
			break
		minpage = i
	pagerange=range(minpage,maxpage+1)
	if request.user.is_authenticated():
		return render(request,'community_index_after_login.html',{"posts":posts,"pagerange":pagerange,})
	else:
		return render(request,'community_index.html',{"posts":posts,"pagerange":pagerange,})

def community_index_mypost(request,page=1):
	if request.user.is_authenticated:
		post_list = Post.objects.filter(sender=request.user)
		paginator = Paginator(post_list,5)
		delete_id = None
		delete_id = request.POST.get('delete_id','')
		try:
			post = Post.objects.get(id=int(delete_id))
			post.delete()
		except Exception:
			pass
		try:
			page = int (request.GET.get('page','1'))
		except ValueError:
			page = 1
		try:
			posts = paginator.page(page)
		except (EmptyPage,InvalidPage):
			posts = paginator.page(paginator.num_pages)
		for i in range(page,page+3):
			if i > paginator.num_pages:
				break
			maxpage = i
		for i in range(page,page-3,-1):
			if i < 1:
				break
			minpage = i
		pagerange=range(minpage,maxpage+1)
		return render(request,'community_index_after_login.html',{"posts":posts,"pagerange":pagerange,})
	else:
		pagerange=range(1,2)
		return render(request,'community_index.html',{"pagerange":pagerange,})




# Create your views here.

EDCW/community/templates/community_index.html
{% load static %}
<!doctype html>
        <!--[if lt IE 7]> <html class="lt-ie9 lt-ie8 lt-ie7" lang="en-US"> <![endif]-->
        <!--[if IE 7]>    <html class="lt-ie9 lt-ie8" lang="en-US"> <![endif]-->
        <!--[if IE 8]>    <html class="lt-ie9" lang="en-US"> <![endif]-->
        <!--[if gt IE 8]><!--> <html lang="zh-CN"> <!--<![endif]-->
        <head>
                <!-- META TAGS -->
                <meta charset="UTF-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
				<meta name="description" content="community">
	            <meta name="author" content="zw">

                <title>第十八届电子设计大赛</title>

                
				
                <!-- Style Sheet-->
                <link rel="shortcut icon" href="{% static 'community/img/电设18.png' %}" />
                <link rel='stylesheet' id='bootstrap-css-css'  href="{% static 'community/css/bootstrap.css' %}"type='text/css' media='all' />
                <link rel='stylesheet' id='responsive-css-css'  href="{% static 'community/css/responsive.css' %}"type='text/css' media='all' /> 
                <!--<link rel='stylesheet' id='pretty-photo-css-css'  href='js/prettyphoto/prettyPhotoaeb9.css?ver=3.1.4' type='text/css' media='all' />-->
                <link rel='stylesheet' id='main-css-css'  href="{% static 'community/css/main.css' %}"type='text/css' media='all' />
                <!--<link rel='stylesheet' id='custom-css-css'  href='css/custom5152.html?ver=1.0' type='text/css' media='all' />-->


                <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
                <!--[if lt IE 9]>
                <script src="js/html5.js"></script></script>
                <![endif]-->
				<style>
				#noreply {
				display:none;
				position:fixed;
				bottom:50%;
				left:50%;
				border: 0.2px solid;
				background-color:#fff;
				width:20%;
				z-index:1000;
				padding:15px;
				}
                </style>


        </head>

        <body>

                <!-- Start of Header -->
                <div class="header-wrapper">
                        <header>
                                <div class="container">
								
                                        <div class="logo-container">
                                                <!-- Website Logo -->
                                                <a href="{% url 'index:index' %}"  id="eesast" style="font-size:17px; font-weight:bold;">
                                                      天赐良机
                                                </a>
                                             
                                        </div>


                                        <!-- Start of Main Navigation -->
                                        <nav class="main-nav">
                                                <div class="menu-top-menu-container">
                                                        <ul id="menu-top-menu" class="clearfix">
                                                                <li><a href="{% url 'index:index' %}">主页</a></li>
                                                                <li><a href="{% url 'index:introduction' %}">赛事介绍</a></li>
                                                                <li><a href="{% url 'teams:index' %}">组建队伍</a></li>
                                                                <li><a href="{% url 'login:login' %}">登录</a></li>
                                                                <li  class="current-menu-item"><a href="{% url 'community:community_index' %}">论坛</a></li>
                                                                <li><a href="{% url 'index:notice' %}">文件</a></li>
																<li><a href="{% url 'index:rule' %}">比赛规则</a></li>
                                                                <li><a href="#">更多</a>
                                                                        <ul class="sub-menu">
                                                                                <li><a href="http://www.eesast.com">关于我们</a></li>
                                                                                <li><a href="{% url 'contact:contact' %}">联系我们</a></li>
                                                                        </ul>
                                                                </li>
                                                        </ul>
														<ul id="menu-top-right" class="clearfix">
														        <li><a href="http://www.eesast.com">电子系科协</a></li>
																<li style="font-family:'HelveticaNeue', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 15px; color: #c1cad1;">自动化系科协</li>
														</ul>
                                                </div>
                                                </div>
                                        </nav>
                                        <!-- End of Main Navigation -->

                                </div>
                        </header>
                </div>
                <!-- End of Header -->

                <!-- Start of Search Wrapper -->
                <div class="search-area-wrapper">
                        <div class="search-area container">
                                <h2 class="search-header">第十八届电子设计大赛</h2>
                                <p class="search-tag-line">开始你的设计</p>
                        </div>
                </div>
                <!-- End of Search Wrapper -->

                <!-- Start of Page Container -->
                <div class="page-container">
                        <div class="container" id="page">
                                <div class="row">

                                        <!-- start of page content -->
                                        <div class="span8 main-listing">

                                                {% if posts %}
												{% for post in posts.object_list %}
												<article class="format-standard type-post hentry clearfix">

                                                        <header class="clearfix">

                                                                <h3 class="post-title">
                                                                        <a href="community_content/{{post.id}}">{{post.title}}</a>
                                                                </h3>

                                                                <div class="post-meta clearfix">
                                                                        <span class="date">{{post.timestamp}}</span>
                                                                        <span class="category"><img alt="" src="{{post.sender.profile.image.url}}" class="avatar avatar-60 photo" style="display:inline; border-radius:25px; height:25px; width:25px;">&nbsp&nbsp {{post.sender}}</span>
                                                                        <span class="comments">{{post.p_comment.count}} 回复</span>
                                                                     
                                                                </div><!-- end of post meta -->

                                                        </header>

                                                        <p>{{post.content}}</p>

                                                </article>
												{% endfor %}
												{% else %}<p>现在没有帖子！</p>
												{% endif %}

                                                <div id="pagination">
													{%if posts.has_previous %}
														<a href="community_index?page={{posts.previous_page_number}}" class="btn">上一页</a>
													{% endif %}
														{% for i in pagerange %}
                                                        <a href="community_index?page=i" class="btn active">{{i}}</a>
                                                        {% endfor %}
                                                    {%if posts.has_next %}
														<a href="community_index?page={{posts.next_page_number}}" class="btn">下一页</a>
													{% endif %}
                                                        <a href="community_index?page={{posts.paginator.num_pages}}" class="btn">最后页</a>
                                                </div>

                                        </div>
                                        <!-- end of page content -->


                                        <!-- start of sidebar -->
                                        <aside class="span4 page-sidebar">

                                                <section class="widget">
                                                        <div class="support-widget">
															{% if request.user.authenticated %}
																<div class="comment-reply-link""><button class="clean-gray"><a href="{% url 'community_create' %}">创建新的帖子</a></button></div>
															{% else %}
                                                                <div onclick = "document.getElementById('noreply').style.display='block'" class="comment-reply-link""><button class="clean-gray">创建新的帖子</button></div>
																
                                                        </div>
                                                </section>

                                                                                                <div id='noreply'>
																								<div class="container">
																								<p style="font-size:20px;">您还没有登录，不能发帖和回复</p>
																								<p style="font-size:20px;"><a href="{% url 'login:login' %}">点此登录</a></p>
																								<p style="font-size:20px;"><a onclick = "document.getElementById('noreply').style.display='none'">退出</a></p>
																								</div>
													
																								
																								</div>
															{% endif %}
													
																								
																								
                                                <section class="widget">
                                                        <h3 class="title">文章分类</h3>
                                                        <ul class="articles">
                                                                <li class="article-entry standard">
                                                                        <h4><a href="{% url 'community:community_index_tongzhi' %}">赛事公告</a></h4>
                                                                        <span class="article-meta">这里有重要的信息不能错过</span>
                                                                </li>
                                                                <li class="article-entry standard">
                                                                        <h4><a href="{% url 'community:community_index_jishu' %}">技术讨论</a></h4>
                                                                        <span class="article-meta">一起探讨技术是一件美妙的事情</span>
                                                                </li>
                                                                <li class="article-entry standard">
                                                                        <h4><a href="{% url 'community:community_index_shuitie' %}" >各路水贴</a></h4>
                                                                        <span class="article-meta">我们来随便聊一聊</span>
                                                                </li>
													
                                                        </ul>
                                                </section>



                                                <section class="widget"><h3 class="title">您还没有登录！</h3>
                                                        
                                                </section>

                                                
                                        </aside>
                                        <!-- end of sidebar -->
                                </div>
                        </div>
                </div>
                <!-- End of Page Container -->



                        <!-- Footer Bottom -->
                        <div id="footer-bottom-wrapper">
                                <div id="footer-bottom" class="container">
                                        <div class="row">
                                                <div class="span6">
                                                        <p class="copyright">
                                                                Copyright © All Rights Reserved by EESAST from Tsinghua
                                                        </p>
                                                </div>
                                                
                                        </div>
                                </div>
                        </div>
                        <!-- End of Footer Bottom -->

                </footer>
                <!-- End of Footer -->

                <a href="#top" id="scroll-top"></a>
				

                <!-- script -->
                <script type='text/javascript' src="{% static 'community/js/jquery.min.js' %}"></script>
				<script type='text/javascript' src="{% static 'community/js/custom.js' %}"></script>
				<script type='text/javascript' src="{% static 'community/js/jflickrfeed.js' %}"></script>
<script type='text/javascript' src="{% static 'community/js/jquery.validate.min.js' %}"></script>

        </body>
</html>