EDCW/EDCW/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'', include('index.urls')),
    url(r'', include('contact.urls')),
    url(r'', include('community.urls')),
    url(r'^team/', include('teams.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'', include('login.urls')),
]

EDCW/community/urls.py
from django.conf.urls import url
from . import views

app_name = 'community'

urlpatterns = [
    url(r'^community_create$',views.community_create,name='community_create'),
    url(r'^community_index$',views.community_index,name='community_index'),
    url(r'^community_index?page=([0-9]+)$',views.community_index,name='community_index'),
    url(r'^community_index_tongzhi$',views.community_index_tongzhi,name='community_index_tongzhi'),
    url(r'^community_index_tongzhi?page=([0-9]+)$',views.community_index_tongzhi,name='community_index_tongzhi'),
    url(r'^community_index_jishu$',views.community_index_jishu,name='community_index_jishu'),
    url(r'^community_index_jishu?page=([0-9]+)$',views.community_index_jishu,name='community_index_jishu'),
    url(r'^community_index_shuitie$',views.community_index_shuitie,name='community_index_shuitie'),
    url(r'^community_index_shuitie?page=([0-9]+)$',views.community_index_shuitie,name='community_index_shuitie'),
    url(r'^community_index_mypost$',views.community_index_mypost,name='community_index_mypost'),
    url(r'^community_index_mypost?page=([0-9]+)$',views.community_index_mypost,name='community_index_mypost'),
    url(r'^community_content/(?P<id>[0-9]+)',views.community_content),
]
# Create your views here.

EDCW/contact/urls.py
from django.conf.urls import url
from . import views

app_name = 'contact'

urlpatterns = [
    url(r'^contact$', views.contact, name='contact'),
]

# Create your views here.

EDCW/index/urls.py
from django.conf.urls import url, include
from . import views
import contact
app_name = 'index'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^introduction$', views.introduction, name='introduction'),
    url(r'^notice$', views.noticeIndex, name='notice'),
    url(r'^rule$', views.rule, name='rule'),
    url(r'^download', views.download, name='download'),
]

EDCW/login/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'login'

urlpatterns = [
    url(r'^login$',views.Login,name='login'),
    ]
urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT )

EDCW/teams/urls.py
from django.conf.urls import url
from . import views

app_name = 'teams'

urlpatterns = [
    url(r'^index$', views.index , name='index'),
    url(r'^create$', views.create, name='create'),
    url(r'^info/(?P<team_id>[0-9]+)$', views.info, name='info'),
    url(r'^application/(?P<team_id>[0-9]+)$', views.application, name='application'),
    url(r'^myteam$', views.my_team, name='my_team'),
    url(r'^answer$', views.acceptOrReject, name='acceptOrReject'),
    url(r'^dismiss$', views.dismiss, name='dismiss'),
    url(r'group$', views.group, name='group'),
    url(r'choose_first_time$', views.choose_first_time, name='choose_first_time')
]

EDCW/teams/models.py
# -*- coding: utf-8 -*-


from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
import datetime

timelist = [datetime.datetime(2016, 11, 19, hour=9, minute=30)
            + i*datetime.timedelta(minutes=6) for i in range(20)]
timelist = timelist + [datetime.datetime(2016, 11, 19, hour=13, minute=30)
                      + i*datetime.timedelta(minutes=6) for i in range(35)]

pre = zip(range(len(timelist)),
          [p.strftime("%d")+'日'+p.strftime("%H:%M")+'---'+(p+datetime.timedelta(minutes=6)).strftime("%H:%M") for p in timelist])
pre_time_choice = [(-1, 'None') ] + [p for p in pre]
					  
timelist = timelist + [datetime.datetime(2016, 11, 20, hour=9, minute=30)
            + i*datetime.timedelta(minutes=6) for i in range(20)]
timelist = timelist + [datetime.datetime(2016, 11, 20, hour=13, minute=30)
                      + i*datetime.timedelta(minutes=6) for i in range(35)]
					  
first = zip(range(len(timelist)),
          [p.strftime("%d")+'日'+p.strftime("%H:%M")+'---'+(p+datetime.timedelta(minutes=6)).strftime("%H:%M") for p in timelist])
first_time_choice = [(-1, 'None') ] + [p for p in first]

fuhuo_time_choice = [(-1,'None')]+[(1, '周六') ] + [(2,'周日')]+[(3, '服从调剂')]


class Team(models.Model):
    DSP = 'D'
    MCU = 'M'
    FPGA = 'F'
    GROUP_CHOICES = (
        (DSP, 'DSP'),
        (MCU, '单片机'),
        (FPGA, 'FPGA'),
    )
    group = models.CharField(
        max_length=1,
        choices=GROUP_CHOICES,
        default='M',
    )
    pre_time = models.IntegerField(choices = pre_time_choice, default=-1)
    first_time = models.IntegerField(choices = first_time_choice, default=-1)
    fuhuo_time = models.IntegerField(choices = fuhuo_time_choice, default=-1, blank=True, null=True)
    name = models.CharField(max_length=20)
    intro = models.CharField(max_length=50)
    leader = models.OneToOneField(User, on_delete=models.CASCADE, related_name='leads')
    members = models.ManyToManyField(User, related_name='in_team')
    is_full = models.BooleanField(default=False)


    def __str__(self):
        return self.name + ' -- ' + self.leader.username

class Application(models.Model):
    applicant = models.ForeignKey(User, on_delete=models.CASCADE)
    team = models.ForeignKey('Team', on_delete=models.CASCADE)
    reason = models.CharField(max_length=200)

    def __str__(self):
        return self.applicant.username + ' --> ' + self.team.name

EDCW/teams/forms.py
from django import forms
from .models import Team, fuhuo_time_choice

class AppForm(forms.Form):
    reason = forms.CharField(max_length=300, required=False)

class CreateForm(forms.Form):
    name = forms.CharField(max_length=20)
    intro = forms.CharField(max_length=50)
    group = forms.ChoiceField(choices=Team.GROUP_CHOICES)


class GroupForm(forms.Form):
    group = forms.ChoiceField(choices=Team.GROUP_CHOICES)



class FuhuoTimeForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(FuhuoTimeForm, self).__init__(*args, **kwargs)
        s = fuhuo_time_choice
        for team in Team.objects.filter(fuhuo_time__gte = 1):
            s = [choice for choice in s if choice[0] != team.fuhuo_time]
        self.fields['choice'].choices = s

    choice = forms.ChoiceField(choices=())
    other = forms.CharField(required=False, max_length=30, widget=forms.TextInput(attrs={'placeholder': u'若都不合适，请输入合适时间'}))

EDCW/teams/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, get_object_or_404
from .models import Team, Application, pre_time_choice
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from .forms import CreateForm, AppForm, GroupForm, FuhuoTimeForm
from django.contrib.auth.decorators import login_required
def if_in_team(user):
    in_team = False
    if user.is_authenticated:
        if user.in_team.all() or user.profile.is_leader:
            in_team = True
    return in_team

def get_user_info(user):
    if user.is_authenticated:
        in_team = if_in_team(user)
        is_leader = user.profile.is_leader
        team = ''
        if is_leader:
            team = user.leads
            app_list = team.application_set.all()
        else:
            teams = user.in_team.all()
            for t in teams:
                if user in t.members.all():
                    team = t
            app_list = []

        return {
                 'in_team': in_team,
                 'is_leader': is_leader,
                 'app_list': app_list,
                 'team': team,
                 'errors': [],
                 'note': '',
        }

    return None


def index(request):
    teams = Team.objects.all()
    usr = request.user
    note = ''
    if not usr.is_authenticated:
        in_team = False
        note = '请登录之后进行操作'
    else:
        in_team = if_in_team(usr)
        if usr.application_set.all():
            in_team = True
            note = '您已经提交申请，请等候队长答复'

    return render(request, 'teams/team_index.html',
                  {'teams': teams,
                   'in_team' : in_team,
                   'note': note
                  })



def info(request, team_id):
    team = get_object_or_404(Team, pk=team_id)
    usr = request.user
    in_team = if_in_team(usr)
    return render(request, 'teams/team_info.html',
                  {'team': team,
                   'in_team': in_team,
                  })

@login_required
def my_team(request):

    # kickout a member in a certain team
    if request.method == 'POST':
        name = request.POST['name']
        team = request.user.leads
        thisone = team.members.get(username=name)
        team.members.remove(thisone)
        if team.members.count() < 3:
            team.is_full = False
            team.save()
        HttpResponseRedirect(reverse('teams:my_team'))

    # specify the certain page
    user = request.user
    user_info_dict = get_user_info(user)

    if user_info_dict:
        form = FuhuoTimeForm()
        user_info_dict['form'] = form
        return render(request, 'teams/team_myteam.html', user_info_dict)

    return HttpResponseRedirect(reverse('teams:index'))


@login_required
def acceptOrReject(request):


    user_info_dict = get_user_info(request.user)

    if request.method == 'POST':
        app_id = request.POST['app_id']
        answer = request.POST['answer']
        app = get_object_or_404(Application, pk=app_id)
        team = app.team
        in_team = if_in_team(app.applicant)
        errors = []

        if answer == 'agree':
            if team.is_full:
                errors.append('本队伍已满, 该申请已自动删除')
            if in_team:
                errors.append('该同学已在某个队伍中，该申请已自动删除')

            if not errors:
                team.members.add(app.applicant)
                if team.members.count() >= 3:
                    team.is_full = True
                    team.save()
                # delete all the applications from this applicant
                Application.objects.filter(applicant=app.applicant).delete()


            user_info_dict['errors'] = errors

        elif answer == 'disagree':

            user_info_dict['note'] = '已拒绝该请求'

        app.delete()

        return render(request, 'teams/team_myteam.html', user_info_dict)

    raise Http404

@login_required
def application(request, team_id):
    team = get_object_or_404(Team, pk=team_id)
    user = request.user
    in_team = if_in_team(user)
    error = ''

    if in_team:
        return HttpResponseRedirect(reverse('teams:index'))


    if request.method =='POST':

        apps = user.application_set.filter(team=team)
        if apps.count():
            error = '您已经申请加入该队伍，请等候队长审核'

        else:
            form = AppForm(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                reason = cd['reason']
                app = Application(applicant=request.user, team=team, reason=reason)
                app.save()
                return HttpResponseRedirect(reverse('teams:index'))



    return render(request, 'teams/team_join.html',
                  {
                      'team' : team,
                      'username' : request.user.username,
                      'in_team' : in_team,
                      'error' : error
                  })

@login_required
def create(request):
    errors = []
    form = CreateForm()
    if request.method == 'POST':
        form = CreateForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            name = cd['name']
            intro = cd['intro']
            choice = cd['group']
            if request.user.in_team.all() or request.user.profile.is_leader:
                errors.append('您已经在队伍中')

            exist = Team.objects.filter(name=name)
            if exist.count():
                errors.append('队名已被使用')

            if errors:
                return render(request, 'teams/team_create.html', {'form': form, 'errors' : errors })

            else:
                team = Team(name=name, intro=intro, leader=request.user, group=choice)
                team.save()
                request.user.profile.is_leader = True
                request.user.profile.save()
                return HttpResponseRedirect(reverse('teams:my_team'))


    return render(request, 'teams/team_create.html', {'form': form})

@login_required
def group(request):

    if request.method == 'POST':
        form = GroupForm(request.POST)
        if form.is_valid():
            team = request.user.leads
            cd = form.cleaned_data
            choice = cd['group']
            team.group = choice
            team.save()

    return HttpResponseRedirect(reverse('teams:my_team'))


@login_required
def dismiss(request):

    if request.method == 'POST':
        user = request.user
        team_id = request.POST['team_id']
        team = get_object_or_404(Team, pk=team_id)
        team.members.clear()
        team.delete()
        user.profile.is_leader = False
        user.profile.save()

    return HttpResponseRedirect(reverse('teams:index'))


@login_required
def choose_first_time(request):

    if request.method == 'POST':
        usr = request.user
        if not usr.profile.is_leader:
            return HttpResponseRedirect(reverse('teams:my_team'))
        team = get_object_or_404(Team, leader=usr)
        form = FuhuoTimeForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            team.fuhuo_time = cd['choice']
            team.save()

    return HttpResponseRedirect(reverse('teams:my_team'))

EDCW/teams/templates/teams/team_index.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="team">
	<meta name="author" content="zw">

<title>第十八届电子设计大赛官网</title>
<link rel="shortcut icon" href="{% static 'teams/img/电设18.png' %}" />

<link rel='stylesheet' id='bootstrap-css-css'  href="{% static 'teams/css/bootstrap.css' %}" type='text/css' media='all' />
                <link rel='stylesheet' id='responsive-css-css'  href="{% static 'teams/css/responsive.css' %}" type='text/css' media='all' /> 
                <!--<link rel='stylesheet' id='pretty-photo-css-css'  href='js/prettyphoto/prettyPhotoaeb9.css?ver=3.1.4' type='text/css' media='all' />-->
                <link rel='stylesheet' id='main-css-css'  href="{% static 'teams/css/team_index.css' %}" type='text/css' media='all' />
                <!--<link rel='stylesheet' id='custom-css-css'  href='css/custom5152.html?ver=1.0' type='text/css' media='all' />-->




<style type="text/css">

a:link {
 text-decoration: none;
}
a:visited {
 text-decoration: none;
}
a:hover {
 text-decoration: none;
}
a:active {
 text-decoration: none;
}

</style> 

</head>

<body>




<!-- Start of Header -->
                <div class="header-wrapper">
                        <header>
                                <div class="container">
								
                                        <div class="logo-container">
                                                <!-- Website Logo -->
                                                <a href="{% url 'index:index' %}"  id="eesast" style="font-size:17px; font-weight:bold;">
                                                      天赐良机
                                                </a>
                                             
                                        </div>


                                        <!-- Start of Main Navigation -->
                                        <nav class="main-nav">
                                                <div class="menu-top-menu-container">
                                                        <ul id="menu-top-menu" class="clearfix">
                                                                <li><a href="{% url 'index:index' %}">主页</a></li>
                                                                <li><a href="{% url 'index:introduction' %}">赛事介绍</a></li>
                                                                <li class="current-menu-item"><a href="{% url 'teams:index' %}">组建队伍</a></li>
																{% if request.user.is_authenticated %}
                                                                <li><a href="{% url 'login:login' %}">用户</a></li>
																{% endif %}
																{% if not request.user.is_authenticated %}
																<li><a href="{% url 'login:login' %}">登录</a></li>
																{% endif %}
                                                                <li><a href="{% url 'community:community_index' %}">论坛</a></li>
                                                                <li><a href="{% url 'index:notice' %}">文件</a></li>
																<li><a href="{% url 'index:rule' %}">比赛规则</a></li>
                                                                <li><a href="#">更多</a>
                                                                        <ul class="sub-menu">
                                                                                <li><a href="http://www.eesast.com" target="_blank">关于我们</a></li>
                                                                                <li><a href="{% url 'contact:contact' %}">联系我们</a></li>
                                                                        </ul>
                                                                </li>
                                                        </ul>
														<ul id="menu-top-right" class="clearfix">
														        <li style="font-size:18px;bold"><a href="{% url 'login:login' %}"> {{request.user.username}}</a></li>
														        <li><a href="http://www.eesast.com" target="_blank">电子系科协</a></li>
																<li style="font-family:'HelveticaNeue', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 15px; color: #c1cad1;">自动化系科协</li>
														</ul>
                                                </div>
                                        </nav>
                                        <!-- End of Main Navigation -->

                                </div>
                        </header>
                </div>
                <!-- End of Header -->


                 <!-- Start of Search Wrapper -->
                <div class="search-area-wrapper">
                        <div class="search-area container">
                                <h2 class="search-header">第十八届电子设计大赛</h2>
                                <p class="search-tag-line">开始你的设计</p>
                        </div>
                </div>
                <!-- End of Search Wrapper -->
				
				
				
				<div class="page-container">
                        <div class="container" id="page">
                                <div class="row">

                                        <!-- start of page content -->
                                        <div class="span12 main-listing">
										       <h2 class="post-title">队伍信息</h2>
											   <table class="table table-striped table-bordered">
											      <thead>
												    <tr>
													  <td>编号</td>
													  <td>队名</td>
													  <td>队长</td>
													  <td>简介</td>
													  <td>成员</td>
                                                      <td>控制器</td>
													  <td>操作</td>
													</tr>
												  </thead>
												  <tbody>
												  {% for team in teams %}
												    <tr>
													  <td>{{ forloop.counter }}</td>
													  <td>{{team.name}}</td>
													  <td>{{team.leader.username}}</td>
													  <td>{{team.intro}}</td>
													  <td>{{team.members.count|add:1}}</td>
                                                      <td>{{team.get_group_display}}
                                                      <td><a href="{% url 'teams:info' team.id %}">查看</a>&nbsp&nbsp
                                                  <!--    {% if not in_team and request.user.is_authenticated and not team.is_full %}
                                                          <a href="{% url 'teams:application' team.id %}">加入</a>
                                                      {% endif %}    -->
													</tr>
												  {% endfor %}
												  </tbody>
												</table>
												
                                                {% if note %}
                                                    <p> {{note}} </p>
                                                {% endif %}
												{% if request.user.is_authenticated %}
                                          <!--          {% if not in_team %}
                                                       <a href="{% url 'teams:create' %}"><button class="btn btn-block btn-info" style="font-size:20px; height:50px;">创建自己的队伍</button></a>
                                                    {% endif %}     -->
                                                    {% if in_team %}
                                                    <a href="{% url 'teams:my_team' %}"><button class="btn btn-block btn-info" style="font-size:20px; height:50px; margin-top:15px;">查看我的队伍</button></a>
                                                    {% endif %}

												{% endif %}
												
												
												
								</div>
						    </div>
						</div>
					</div>
													  
													  
					<!-- Footer Bottom -->
                        <div id="footer-bottom-wrapper">
                                <div id="footer-bottom" class="container">
                                        <div class="row">
                                                <div class="span6">
                                                        <p class="copyright">
                                                                Copyright © All Rights Reserved by EESAST from Tsinghua
                                                        </p>
                                                </div>
                                                
                                        </div>
                                </div>
                        </div>
                        <!-- End of Footer Bottom -->

                </footer>
                <!-- End of Footer -->

                <a href="#top" id="scroll-top"></a>
				

                <!-- script -->

                <script type='text/javascript' src="{% static 'teams/js/jquery.min.js' %}"></script>
				<script type='text/javascript' src="{% static 'teams/js/custom.js' %}"></script>
				<script type='text/javascript' src="{% static 'teams/js/jflickrfeed.js' %}"></script>
<script type='text/javascript' src="{% static 'teams/js/jquery.validate.min.js' %}"></script>


        </body>
</html>
										
										
										
										
										
										

EDCW/teams/templates/teams/team_info.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="team">
	<meta name="author" content="zw">

<title>第十八届电子设计大赛官网</title>

<!-- Bootstrap core CSS -->
<link rel="shortcut icon" href="{% static 'teams/img/电设18.png' %}" />
<link rel='stylesheet' id='bootstrap-css-css'  href="{% static 'teams/css/bootstrap.css' %}" type='text/css' media='all' />
<link href="{% static 'teams/css/team_index.css' %}"  rel="stylesheet">
<link rel='stylesheet' id='responsive-css-css'  href="{% static 'teams/css/responsive.css' %}" type='text/css' media='all' />






<style type="text/css">

a:link {
 text-decoration: none;
}
a:visited {
 text-decoration: none;
}
a:hover {
 text-decoration: none;
}
a:active {
 text-decoration: none;
}

</style> 
</head>
<body>



<!-- Start of Header -->
                <div class="header-wrapper">
                        <header>
                                <div class="container">
								
                                        <div class="logo-container">
                                                <!-- Website Logo -->
                                                <a href="{% url 'index:index' %}"  id="eesast" style="font-size:17px; font-weight:bold;">
                                                      天赐良机
                                                </a>
                                             
                                        </div>


                                        <!-- Start of Main Navigation -->
                                        <nav class="main-nav">
                                                <div class="menu-top-menu-container">
                                                        <ul id="menu-top-menu" class="clearfix">

                                                               <li><a href="{% url 'index:index' %}">主页</a></li>
                                                                <li><a href="{% url 'index:introduction' %}">赛事介绍</a></li>
                                                                <li class="current-menu-item"><a href="{% url 'teams:index' %}">组建队伍</a></li>
																{% if request.user.is_authenticated %}
                                                                <li><a href="{% url 'login:login' %}">用户</a></li>
																{% endif %}
																{% if not request.user.is_authenticated %}
																<li><a href="{% url 'login:login' %}">登录</a></li>
																{% endif %}
                                                                <li><a href="{% url 'community:community_index' %}">论坛</a></li>
                                                                <li><a href="{% url 'index:notice' %}">文件</a></li>
																<li><a href="{% url 'index:rule' %}">比赛规则</a></li>
                                                                <li><a href="#">更多</a>
                                                                        <ul class="sub-menu">
                                                                                <li><a href="http://www.eesast.com">关于我们</a></li>
                                                                                <li><a href="{% url 'contact:contact' %}">联系我们</a></li>
                                                                        </ul>
                                                                </li>
                                                        </ul>
														<ul id="menu-top-right" class="clearfix">
														        <li style="font-size:18px;bold">Welcome!<a href="{% url 'login:login' %}"> {{request.user.username}}</a></li>
														        <li><a href="http://www.eesast.com" target="_blank">电子系科协</a></li>
																<li style="font-family:'HelveticaNeue', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 15px; color: #c1cad1;">自动化系科协</li>
														</ul>
                                                </div>
                                        </nav>
                                        <!-- End of Main Navigation -->


                                </div>
                        </header>
                </div>
                <!-- End of Header -->


                 <!-- Start of Search Wrapper -->
                <div class="search-area-wrapper">
                        <div class="search-area container">
                                <h2 class="search-header">第十八届电子设计大赛</h2>
                                <p class="search-tag-line">开始你的设计</p>
                        </div>
                </div>
                <!-- End of Search Wrapper -->
				
				
				
				<div class="page-container">
                        <div class="container" id="page">
                                <div class="row">

                                        <!-- start of page content -->
                                        <div class="span12 main-listing">
										       <h2 class="post-title">队伍信息</h2>
											   <table class="table table-striped table-bordered">
											        <tbody>
												    <tr>
													  <td style="font-weight:bold;">队名</td>
													  <td>{{team.name}}</td>
													</tr>
													<tr>
													  <td style="font-weight:bold;">简介</td>
													  <td>{{team.intro}}</td>
													</tr>
													<tr>
													  <td style="font-weight:bold;">队长</td>
													  <td>{{team.leader.username}}</td>
													</tr>
													<tr>
													  <td style="font-weight:bold;">成员数</td>
													  <td>{{team.members.count|add:1}}</td>
													</tr>
													{% for member in team.members.all %}
													<tr>
													  <td style="font-weight:bold;">成员</td>
													  <td>{{member.username}}</td>
													</tr>
													{% endfor %}
													<tr>
													  <td style="font-weight:bold;">控制器</td>
                                                      <td>{{team.get_group_display}}</td>
													</tr>
													</tbody>
											   </table>
											   
                                <!--               {% if not in_team and request.user.is_authenticated and not team.is_full %}
                                               <a href="{% url 'teams:application' team.id %}"><button class="btn btn-block btn-info" style="font-size:20px; height:50px;">申请加入该队伍</button></a>
                                               {% endif %}           -->
									</div>
								</div>
							</div>
						</div>
													
				<!-- Footer Bottom -->
                        <div id="footer-bottom-wrapper">
                                <div id="footer-bottom" class="container">
                                        <div class="row">
                                                <div class="span6">
                                                        <p class="copyright">
                                                                Copyright © All Rights Reserved by EESAST from Tsinghua
                                                        </p>
                                                </div>
                                                
                                        </div>
                                </div>
                        </div>
                        <!-- End of Footer Bottom -->

                </footer>
                <!-- End of Footer -->

                <a href="#top" id="scroll-top"></a>
				

                <!-- script -->

                <script type='text/javascript' src="{% static 'teams/js/jquery.min.js' %}"></script>
				<script type='text/javascript' src="{% static 'teams/js/custom.js' %}"></script>
				<script type='text/javascript' src="{% static 'js/jflickrfeed.js' %}"></script>
<script type='text/javascript' src="{% static 'js/jquery.validate.min.js' %}"></script>


        </body>
</html>