EDCW/EDCW/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'', include('index.urls')),
    url(r'', include('contact.urls')),
    url(r'', include('community.urls')),
    url(r'^team/', include('teams.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'', include('login.urls')),
]

EDCW/contact/urls.py
from django.conf.urls import url
from . import views

app_name = 'contact'

urlpatterns = [
    url(r'^contact$', views.contact, name='contact'),
]

# Create your views here.

EDCW/index/urls.py
from django.conf.urls import url, include
from . import views
import contact
app_name = 'index'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^introduction$', views.introduction, name='introduction'),
    url(r'^notice$', views.noticeIndex, name='notice'),
    url(r'^rule$', views.rule, name='rule'),
    url(r'^download', views.download, name='download'),
]

EDCW/login/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'login'

urlpatterns = [
    url(r'^login$',views.Login,name='login'),
    ]
urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT )

EDCW/teams/urls.py
from django.conf.urls import url
from . import views

app_name = 'teams'

urlpatterns = [
    url(r'^index$', views.index , name='index'),
    url(r'^create$', views.create, name='create'),
    url(r'^info/(?P<team_id>[0-9]+)$', views.info, name='info'),
    url(r'^application/(?P<team_id>[0-9]+)$', views.application, name='application'),
    url(r'^myteam$', views.my_team, name='my_team'),
    url(r'^answer$', views.acceptOrReject, name='acceptOrReject'),
    url(r'^dismiss$', views.dismiss, name='dismiss'),
    url(r'group$', views.group, name='group'),
    url(r'choose_first_time$', views.choose_first_time, name='choose_first_time')
]

EDCW/index/templates/index/notice.html
{% load static %}
<!doctype html>
        <!--[if lt IE 7]> <html class="lt-ie9 lt-ie8 lt-ie7" lang="en-US"> <![endif]-->
        <!--[if IE 7]>    <html class="lt-ie9 lt-ie8" lang="en-US"> <![endif]-->
        <!--[if IE 8]>    <html class="lt-ie9" lang="en-US"> <![endif]-->
        <!--[if gt IE 8]><!--> <html lang="zh-CN"> <!--<![endif]-->
        <head>
                <!-- META TAGS -->
                <meta charset="UTF-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
				<meta name="description" content="notice">
	            <meta name="author" content="zw">

                <title>第十八届电子设计大赛</title>

                
				
                <!-- Style Sheet-->
                <link rel="shortcut icon" href="{% static 'index/img/电设18.png' %}" />
                <link rel='stylesheet' id='bootstrap-css-css'  href="{% static 'index/css/bootstrap.css' %}" type='text/css' media='all' />
                <link rel='stylesheet' id='responsive-css-css'  href="{% static 'index/css/responsive.css' %}" type='text/css' media='all' /> 
                <!--<link rel='stylesheet' id='pretty-photo-css-css'  href='js/prettyphoto/prettyPhotoaeb9.css?ver=3.1.4' type='text/css' media='all' />-->
                <link rel='stylesheet' id='main-css-css'  href="{% static 'index/css/file.css' %}" type='text/css' media='all' />
                <!--<link rel='stylesheet' id='custom-css-css'  href='css/custom5152.html?ver=1.0' type='text/css' media='all' />-->


                <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
                <!--[if lt IE 9]>
                <script src="js/html5.js"></script></script>
                <![endif]-->


        </head>

        <body>

                <!-- Start of Header -->
                <div class="header-wrapper">
                        <header>
                                <div class="container">
								
                                        <div class="logo-container">
                                                <!-- Website Logo -->
                                                <a href="{% url 'index:index' %}"  id="eesast" style="font-size:17px; font-weight:bold;">
                                                      天赐良机
                                                </a>
                                             
                                        </div>


                                                                               <!-- Start of Main Navigation -->
                                        <nav class="main-nav">
                                                <div class="menu-top-menu-container">
                                                        <ul id="menu-top-menu" class="clearfix">
                                                            <li><a href="{% url 'index:index' %}">主页</a></li>
                                                                <li><a href="{% url 'index:introduction' %}">赛事介绍</a></li>
                                                                <li><a href="{% url 'teams:index' %}">组建队伍</a></li>
                                                                {% if request.user.is_authenticated %}
                                                                <li><a href="{% url 'login:login' %}">用户</a></li>
																{% endif %}
																{% if not request.user.is_authenticated %}
																<li><a href="{% url 'login:login' %}">登录</a></li>
																{% endif %}
                                                                <li><a href="{% url 'community:community_index' %}">论坛</a></li>
                                                                <li  class="current-menu-item"><a href="{% url 'index:notice' %}">文件</a></li>
																<li><a href="{% url 'index:rule' %}">比赛规则</a></li>
                                                                <li><a href="#">更多</a>
                                                                        <ul class="sub-menu">
																		        {% if request.user.is_authenticated %}
                                                                                <li style="font-size:18px;bold"><a href="{% url 'login:login' %}"> {{request.user.username}}</a></li>
																                {% endif %}
                                                                                <li><a href="http://www.eesast.com" target="_blank">关于我们</a></li>
                                                                                <li><a href="{% url 'contact:contact' %}">联系我们</a></li>
                                                                        </ul>
                                                                </li>
                                                        </ul>
														<ul id="menu-top-right" class="clearfix">
														        {% if request.user.is_authenticated %}
                                                                                <li style="font-size:18px;bold"><a href="{% url 'login:login' %}"> {{request.user.username}}</a></li>
																{% endif %}
														        <li><a href="https://www.eesast.com" target="_blank">电子系科协</a></li>
																<li style="font-family:'HelveticaNeue', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 15px; color: #c1cad1;">自动化系科协</li>
														</ul>
                                                </div>
                                        </nav>
                                        <!-- End of Main Navigation -->

                                </div>
                        </header>
                </div>
                <!-- End of Header -->

                <!-- Start of Search Wrapper -->
                <div class="search-area-wrapper">
                        <div class="search-area container">
                                <h2 class="search-header">第十八届电子设计大赛</h2>
                                <p class="search-tag-line">开始你的设计</p>
                        </div>
                </div>
                <!-- End of Search Wrapper -->
 <div class="page-container">
 <div class="container-fluid bs-docs-container" id="page">

      <div class="row">
	    <div class="span2" role="complementary" id="btn-block">
		 
		
		</div>
		<div role="file" id="file-block" class="span8">
		{% if notice_list %}	
        {% load myfilter %}
		    {% for notice in notice_list %}
			  <div id="notice">
              <li id="lititle">{{notice.title}}</li>
              <p id="licontent" style="margin-top:10px;">{{notice.content}}</p>
			  {% if notice.file_attached %}
              <p id="file">文件：<a href="{{ notice.file_attached.name|filelink }}">{{ notice.file_attached.name|filename }}</a></p>

			  {% endif %} 
			  </div>
            {% endfor %} 
              {% else %} 
                <p  id="licontent" style="margin-top:10px;"> No Notices </p> 
         {% endif %} 

		 
          			
		</div>
	  </div>
	  
	  
		
		
		
		
    </div>
	</div>
	<!-- Footer Bottom -->
                        <div id="footer-bottom-wrapper">
                                <div id="footer-bottom" class="container">
                                        <div class="row">
                                                <div class="span6">
                                                        <p class="copyright">
                                                                Copyright © All Rights Reserved by EESAST from Tsinghua
                                                        </p>
                                                </div>
                                                
                                        </div>
                                </div>
                        </div>
                        <!-- End of Footer Bottom -->

                </footer>
                <!-- End of Footer -->

                <a href="#top" id="scroll-top"></a>
	<!-- script -->
                <script type='text/javascript' src="{% static 'index/js/jquery.min.js' %}"></script>
                <script type='text/javascript' src="{% static 'index/js/custom.js' %}"></script>
				<script type='text/javascript' src="{% static 'index/js/jflickrfeed.js' %}"></script>
<script type='text/javascript' src="{% static 'index/js/jquery.validate.min.js' %}"></script>
  </body>
  </html>

EDCW/index/templates/index/notice_aux.html
{% load static %}
{% if notice_list %}
 
<form action="{% url 'index:download' %}" method="post">
{% csrf_token %}
  {% for notice in notice_list %}
    <li>{{ notice.title }}</li>
    <li>{{ notice.content }}</li>
    {% if notice.file_attached %}
      <input type="submit" name="choice" value="{{ notice.id }}">
    {% endif %}
  {% endfor %}
</form>
{% else %}
    <p> No Notices </p>
{% endif %}

EDCW/index/templates/index/rule.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="rule">
	<meta name="author" content="zw">

<title>第十八届电子设计大赛官网</title>

<!-- Bootstrap core CSS -->
<link rel="shortcut icon" href="{% static 'index/img/电设18.png' %}" />
<link rel='stylesheet' id='bootstrap-css-css'  href="{% static 'index/css/bootstrap.css' %}" type='text/css' media='all' />
<link href="{% static 'index/css/docs.min.css' %}" rel="stylesheet" type='text/css' media='all'/>
<link href="{% static 'index/css/rule.css' %}" rel="stylesheet"/>
<link rel='stylesheet' id='responsive-css-css'  href="{% static 'index/css/responsive.css' %}" type='text/css' media='all' />




<style type="text/css">

a:link {
 text-decoration: none;
}
a:visited {
 text-decoration: none;
}
a:hover {
 text-decoration: none;
}
a:active {
 text-decoration: none;
}

</style> 

</head>
<body>




<!-- Start of Header -->
                <div class="header-wrapper">
                        <header>
                                <div class="container">
								
                                        <div class="logo-container">
                                                <!-- Website Logo -->
                                                <a href="{% url 'index:index' %}"  id="eesast" style="font-size:17px; font-weight:bold;">
                                                      天赐良机
                                                </a>
                                             
                                        </div>


                                        <!-- Start of Main Navigation -->
                                        <nav class="main-nav">
                                                <div class="menu-top-menu-container">
                                                        <ul id="menu-top-menu" class="clearfix">
                                                                <li><a href="{% url 'index:index' %}">主页</a></li>
                                                                <li><a href="{% url 'index:introduction' %}">赛事介绍</a></li>
                                                                <li><a href="{% url 'teams:index' %}">组建队伍</a></li>
                                                                <li><a href="{% url 'login:login' %}">登录</a></li>
                                                                <li><a href="{% url 'community:community_index' %}">论坛</a></li>
                                                                <li><a href="{% url 'index:notice' %}">文件</a></li>
																<li  class="current-menu-item"><a href="{% url 'index:rule' %}">比赛规则</a></li>
                                                                <li><a href="#">更多</a>
                                                                        <ul class="sub-menu">
                                                                                <li><a href="http://www.eesast.com" target="_blank">关于我们</a></li>
                                                                                <li><a href="{% url 'contact:contact' %}">联系我们</a></li>
                                                                        </ul>
                                                                </li>
                                                        </ul>
														<ul id="menu-top-right" class="clearfix">
														        {% if request.user.is_authenticated %}
                                                                                <li style="font-size:18px;bold"><a href="{% url 'login:login' %}"> {{request.user.username}}</a></li>
																                {% endif %}
														        <li><a href="https://www.eesast.com">电子系科协</a></li>
																<li style="font-family:'HelveticaNeue', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 15px; color: #c1cad1;">自动化系科协</li>
														</ul>
                                                </div>
                                        </nav>
                                        <!-- End of Main Navigation -->

                                </div>
                        </header>
                </div>
                <!-- End of Header -->


                 <!-- Start of Search Wrapper -->
                <div class="search-area-wrapper">
                        <div class="search-area container">
                                <h2 class="search-header">第十八届电子设计大赛</h2>
                                <p class="search-tag-line">开始你的设计</p>
                        </div>
                </div>
                <!-- End of Search Wrapper -->
				
				
				 <!-- Start of Page Container -->
                <div class="page-container" id="rule">
                        <div class="container" id="page">
                                <div class="row">
								
								    <div class="span12 main-listing">
									  <article class="page type-page hentry clearfix">
									    <h1 class="post-title">规则</h1>
										<hr>
										<p style="font-size:18px; color:black; font-family:SimSun;">比赛采取1V1对抗模式，在黑白两色图案组成的地图中进行。</p>
										<p style="font-size:18px; color:black; font-family:SimSun;">小车以抢点为主要目标。比赛过程中，目标点、道具、无人机等多种因素都会影响小车生命值。</p>
										<p style="font-size:18px; color:black; font-family:SimSun;">一方生命值归零或时间用尽时比赛结束。结束时生命值较多的队伍获胜。</p>
										
										
										
										
										
										<br>
										<h3>小车</h3>
										<hr>
										<ul  class="xiaoche">
<li>官方提供

<ul>
<li>框架（亚克力板，铜柱）。

<ul>
<li>静态长宽禁止超过20cm。</li>
<li>允许对框架的合理改装（钻孔、重新组合等）。允许自行设计框架结构。</li>
</ul></li>
<li>控制器（单片机/FPGA/DSP）

<ul>
<li>比赛时，禁止和自己的电脑等外部设备进行交互。</li>
<li>不能使用Arduino。</li>
</ul></li>
<li>电机

<ul>
<li>必须使用官方规定型号的电机</li>
</ul></li>
<li>通讯板

<ul>
<li>比赛时，必须使用官方通讯板</li>
<li>比赛时，禁止干扰通讯模块</li>
</ul></li>
<li>定位色块

<ul>
<li>比赛时，必须安装定位色块</li>
<li>比赛时，禁止干扰定位模块</li>
</ul></li>
</ul></li>
<li>自行设计

<ul>
<li>传感器

<ul>
<li>允许使用现成的模块。</li>
</ul></li>
<li>驱动电路板

<ul>
<li>禁止抄袭PCB设计。</li>
<li>不能使用现成的模块。</li>
<li>可以在李兆基大楼印制。可以外包制作。</li>
</ul></li>
<li>其他合理的机械结构

<ul>
<li>静态时（复位时）长宽禁止超过20cm</li>
<li>禁止使用锐器。禁止破坏场地。</li>
</ul></li>
</ul></li>
<li>允许合理的物理对抗

<ul>
<li>允许合理的碰撞、推挤、冲击。</li>
<li>禁止破坏对方小车物理结构，包括破坏框架，破坏连线，造成短路等。</li>
<li>禁止限制对方小车行动，包括架空动力轮，锁死小车，掀翻小车等。</li>
<li>禁止使用水、墨等破坏小车或地图。</li>
</ul></li>
</ul>
<br>

										<h3>地图和定位</h3>
										<hr>
										<ul  class="xiaoche">
<li>地图尺寸为2.56m*2.56m，由黑白两色组成。

<ul>
<li>不保证黑色或白色区域连续。如果尝试寻迹，请注意寻迹策略的选择。</li>
</ul></li>
<li>在定位尺寸为256*256，即一个单位为1cm。

<ul>
<li>定位信息将持续通过通讯模块告知选手。XY两个坐标的范围为0x00~0xFF。注意地图XY坐标默认为<strong>左手系</strong>，请以实际场地为准。</li>
</ul></li>
<li>当选手出界时，通讯模块会发出出界警告。

<ul>
<li>越界的X或Y坐标会保持0x00或0xFF（由出界方向决定），未越界的坐标仍然保持尽可能正确的值。</li>
<li>出界时，小车将受到持续4HP/s伤害。</li>
<li>处于出界状态时，小车以尽可能正确的坐标参与地图逻辑。即占点、道具、无人机等活动仍然有效。</li>
</ul></li>
</ul>
										
										<br>
										<h3>目标点</h3>
										<hr>
										<ul  class="xiaoche">
<li>目标点

<ul>
<li>同一时刻最多只有一个。</li>
<li>位置随机，所在坐标的地图颜色决定了目标点的颜色。</li>
<li>争抢完毕后自动消失，消失后一段时间内自动刷新。</li>
</ul></li>
<li>占点：目标点存在时，总有一或零辆小车处于占点状态。非占点的一或两辆小车将持续扣除生命值。

<ul>
<li>小车的初始血量为200HP。小车的血量范围为0HP~200HP。</li>
<li>小车所在点的颜色和目标点颜色相同即可占点；若两辆小车的颜色都正确，则距离目标点比较近为占点。</li>
<li>当占点小车距离目标点的距离小于20单位时，非占点小车以8HP/s的速度扣血。否则，非占点的小车以2HP/s的速度扣血。</li>
<li>非占点小车受到的伤害，称为目标点造成的伤害。当一个目标点累积造成40HP伤害后，目标点消失。

<ul>
<li>一个目标点存在的时长为5s~20s。</li>
</ul></li>
<li>在目标点消失之后3s，随机产生一个新的目标点。</li>
</ul></li>
</ul>
										
										<br>
										
										<h3>无人机</h3>
										<hr>
										<p>完整的无人机规则只适用于决赛。合适时无人机将由上位机模拟以进行测试。</p>
										<ul class="xiaoche">
<li>无人机有攻击和治疗两种状态，对其投影点附近一定范围内的小车产生影响。选手可通过通讯模块获得无人机的位置坐标。</li>
<li>无人机状态由当前目标点颜色决定：

<ul>
<li>目标点为黑色：无人机变为攻击状态，半径37.5单位，攻击速度8HP/s。<em>在争抢目标点时配合使用杀伤力极大。</em></li>
<li>目标点为白色：无人机变为治疗状态，半径60单位，回复速度4HP/s。<em>可以大大延长游戏的时间。</em></li>
<li>目标点消失时，无人机状态保持不变。</li>
</ul></li>
<li>无人机在默认情况下自动巡航地图。当选手使用道具制空权时，选手可以利用通讯模块发送指令指定无人机的目标点，控制无人机的行动。</li>
</ul>
										
										<br>
										<h3>道具</h3>
										<hr>
										<ul class="xiaoche">
<li>恢复生命

<ul>
<li>立即增加生命值40HP。</li>
</ul></li>
<li>黑白颠倒

<ul>
<li>当前目标点立即消失，并立即产生一个和当前目标点颜色不同的目标点，飞机状态也立即随之改变。

<ul>
<li>若当前目标点不存在，参考当前无人机的状态颜色。</li>
<li><em>总之可以立即刷出一个明确知道颜色的目标点。</em></li>
</ul></li>
</ul></li>
<li>制空权

<ul>
<li>小车可以在10s内控制无人机的行动。</li>
<li>此道具的使用意味着上一次制空权的效果立即终止。</li>
</ul></li>
<li>场上最多有一个道具。</li>
<li>小车只要距离道具在20单位内，道具立即自动生效。</li>
<li>道具的冷却时间为3s。</li>
<li>如果持续15s道具都没有被吃掉，道具会自动刷新。</li>
</ul>
										
										<br>
										<h3>通讯</h3>
										<hr>
										<ul class="xiaoche">
<li>请参考通讯协议。</li>
<li>坐标分辨率一律为0x00~0xFF，这样16位可以表示一个二维坐标。</li>
<li>上位机-&gt;小车

<ul>
<li>小车坐标(16*2)</li>
<li>目标点坐标(16)</li>
<li>无人机的投影坐标(16)</li>
<li>小车的血量(8*2)</li>
<li>道具坐标(16)</li>
<li>道具类型(2)</li>
<li>游戏时间(14)</li>
<li>小车的状态

<ul>
<li>目标点是否存在(1)，目标点颜色(1)</li>
<li>受到目标点伤害(1)，受到大量的目标点伤害(1)</li>
<li>是否受到飞机伤害(1)</li>
<li>是否被飞机回血(1)</li>
<li>自己是否正在控制飞机(1)</li>
</ul></li>
</ul></li>
<li>小车-&gt;上位机

<ul>
<li>无人机目标点坐标(16)</li>
</ul></li>
</ul>

<br>
										<h3>请求暂停</h3>
										<hr>
										<p>裁判可以自由暂停比赛。</p>

<p>在比赛开始后，若出现以下情况，选手可以主动请求暂停：</p>

<ul>
<li>小车出界</li>
<li>小车结构损坏</li>
<li>小车出现其他异常行为<br></li>
</ul>

<p>在一次正式比赛中，每队选手可以在比赛中向裁判<strong>2次</strong>请求暂停。</p>

<ul>
<li>裁判可以先暂停比赛，再考虑是否驳回。若被驳回，视作选手失去1次请求暂停机会。</li>
<li>当暂停生效时，若<strong>请求方</strong>的小车处于出界状态，<strong>请求方</strong>小车瞬间受到40HP惩罚。</li>
<li>暂停生效后，从裁判指示的30s时间内，<strong>双方</strong>选手可以接触和修复自己的小车，并在指定时间内放回到场地内。</li>
</ul>


<br>
<h1 class="post-title">规则整理</h1>
<hr>
<br>
<h3>标准规则</h3>
<br>
<h4>血量</h4>
<ul class="xiaoche">
<li>所在点颜色：黑；白</li>
<li>出界：无0HP/s；出界-4HP/s；暂停 -40HP</li>
<li>目标点：抢到0HP/s；普攻 -2HP/s；暴击 -8HP/s</li>
<li>目标点血量：40HP</li>
<li>无人机：无0HP/s；回复 +4HP/s；攻击 -8HP/s</li>
<li>无人机控制权：有；无</li>
<li>道具：回复+40HP</li>
<li>小车血量：上限200HP，下限0HP</li>
</ul>
<br>

<h4>距离量</h4>
<ul class="xiaoche">
<li>地图尺寸：256</li>
<li>无人机：攻击半径37.5，治疗半径60</li>
<li>目标点：近占半径20</li>
<li>道具：接触半径20，产生道具的回避距离90，产生道具回避边界距离20</li>
<li>距离计算用欧氏距离。</li>
</ul>
<br>

<h4>时间量</h4>
<ul class="xiaoche">
<li>逻辑频率 10Hz</li>
<li>总时间 180s</li>
<li>制空权时间 10s</li>
<li>目标点冷却时间 3s</li>
<li>道具冷却时间 3s，道具自动刷新时间 15s</li>
</ul>
<br>

<h4>胜负判定</h4>
<ol class="xiaoche">
<li>KO对手时剩余的时间长度。</li>
<li>比赛时间耗尽时，双方的血量差距。</li>
</ol>
<br>

<h3>样车规则</h3>
<br>
<h4>血量</h4>
<ul class="xiaoche">
<li>所在点颜色：黑-8HP/s；白-2HP/s</li>
<li>出界：无0HP/s；出界-4HP/s；暂停 -40HP</li>
<li>目标点不存在</li>
<li>无人机不存在</li>
<li>道具：回复+40HP</li>
<li>小车血量：没有上下限</li>
</ul>
<br>
<h4>胜负判定</h4>
<p>比赛时间耗尽时，剩余血量。</p>
<br>

										
										<br>
										<h1 class="post-title">赛程</h1>
										<hr>
										<br>
										<h3>开发套件领取</h3>
										<hr>
										
										<p style="font-size:18px; color:black; font-family:SimSun;">第4周 10.4 ~</p>
										<br>
										<h3>预审</h3>
										<hr>
										<p>第6周周日 10.23</p>

<ul>
<li>一场测试只有一组选手参加。</li>
<li>地图中存在环形通路。</li>
<li>不涉及无人机。</li>
</ul>

<p>以下是评级标准。<em>评级只影响初赛分组。</em></p>

<ul>
<li>A: 能抢点

<ul>
<li>能够在目标点消失前(5s~20s)移动到目标点范围内(20单位)，并在目标点上等待目标点的消失。之后再进行下一个目标点的争抢。需要有明显的停止动作。重复完成以上动作2次及以上。</li>
<li>等价完成条件：完成了通讯模块的接收，小车能够按照抢点算法完成抢点。</li>
</ul></li>
<li>B: 能绕场

<ul>
<li>在白色/黑色区域内绕场2圈及以上。</li>
<li>等价完成条件：完成了红外传感器（或者通讯模块的接收），单片机能够利用传感器输入决策和控制电机。</li>
</ul></li>
<li>C: 能行动

<ul>
<li>能够在地图范围内依次完成前进和转弯动作。</li>
<li>等价完成条件：单片机能够控制电机。</li>
</ul></li>
<li>D: 能动

<ul>
<li>等价完成条件：小车结构完成，电机功能正常。</li>
</ul></li>
</ul>

<p>在预审中，如果使用了现成的电机驱动模块（初赛决赛中不得使用），评级降低一档。</p>
										
										<br>
										<h3>初赛</h3>
										<p style="font-size:18px; color:black; font-family:SimSun;">第9周周末 11.12/11.13</p>
										<p style="font-size:18px; color:black; font-family:SimSun;">初赛中，必须使用自行设计的电机驱动板。</p>
										<h4>小组赛（3组分别取前四）</h4>
										<ul>
<li>分为3组，按照预赛分组平均分配，每组使用一张不同的地图。</li>
<li>所有选手都和样车进行对战，使用<strong>样车规则</strong>，按照180s后的血量进行排名。</li>
<li>每组1~4名进入决赛，5~6名进入复活赛。</li>
</ul>

<h4>复活赛（六进四）</h4>
<ul>
<li>抽签分为3+3两组。</li>
<li>每个小组进行循环赛，每组3场比赛分别使用3张地图，使用<strong>标准规则</strong>。</li>
<li>每组前1~2名进入决赛。</li>
</ul>
										
										<h3>决赛</h3>
										<p style="font-size:18px; color:black; font-family:SimSun;">初定日期 11.27</p>
										<p style="font-size:18px; color:black; font-family:SimSun;">淘汰赛</p>
										
										
										
										
								</article>
							</div>
						</div>
					</div>
				</div>
				
				
				<!-- Footer Bottom -->
                        <div id="footer-bottom-wrapper">
                                <div id="footer-bottom" class="container">
                                        <div class="row">
                                                <div class="span6">
                                                        <p class="copyright">
                                                                Copyright © All Rights Reserved by EESAST from Tsinghua
                                                        </p>
                                                </div>
                                                
                                        </div>
                                </div>
                        </div>
                        <!-- End of Footer Bottom -->

                </footer>
                <!-- End of Footer -->

                <a href="#top" id="scroll-top"></a>
				

                <!-- script -->
<script src="{% static 'index/js/jquery.min.js' %}"></script>
<script type='text/javascript' src="{% static 'index/js/custom.js' %}"></script>
<script type='text/javascript' src="{% static 'index/js/jflickrfeed.js' %}"></script>
<script type='text/javascript' src="{% static 'index/js/jquery.validate.min.js' %}"></script>

        </body>
</html>
										
										

										
										
											  
										  
										
										
										
										
										
										  
										  
										
										
										
										    

										
										   
										  
									  